version: '3'
services:
  kantsu-app:
    container_name: kantsu-app
    restart: always
    build: .
    ports:
      - '15003:5003'
    links:
      - kantsu-redis
    depends_on:
      - kantsu-redis
    environment:
      TZ: Asia/Tokyo
      WAIT_HOSTS: kantsu-redis:6379
  kantsu-redis:
    container_name: kantsu-redis
    image: 'redis:5.0.8'
    restart: always
