version: '3'
services:
  kantsu:
    container_name: kantsu
    restart: always
    build: .
    ports:
      - '5003:5003'
    links:
      - redis
    depends_on:
      - redis
    environment:
      TZ: Asia/Tokyo
      WAIT_HOSTS: kantsu-redis:6379
  redis:
    container_name: kantsu-redis
    image: 'redis:5.0.8'
    restart: always
