default:
  PORT: 5003
  COOKIE_SECRET: tekito
  APP_NAME: 'eroterest-helper'
  SITE_URL: 'https://127.0.0.1:5003'
  MONGODB_URI: "mongodb://127.0.0.1/eroterest-helper"

production: &production
  PORT: #{process.env.PORT}
  COOKIE_SECRET: #{process.env.COOKIE_SECRET}
  APP_NAME: 'eroterest-helper'
  SITE_URL: #{process.env.SITE_URL}
  MONGODB_URI: "mongodb://127.0.0.1/eroterest-helper"